### ISSUE TITLE
consider bluebird for Promise and enable developer warnings

### ISSUE THREAD

**Issue by baffo32** [OpenBCI/OpenBCI_NodeJS#112]
Using bluebird may create more robust code: http://bluebirdjs.com/docs/features.html#debuggability-and-error-handling

**Comment by baffo32** [comment]
bluebird is compatible with other promise libraries, but would create an additional dependency that users of the library would have to install; it could alternatively be used only for tests and the dependency saved, but that would deny developers of its additional features

**Comment by aj-ptw** [comment]
Yea but it wouldn't result in a breaking change right

**Comment by baffo32** [comment]
It would break obscure uses that don't limit themselves to the public promise API specification.

Right now I'm working on a change that uses bluebird only for testing.

**Comment by baffo32** [comment]
I'll close this since it's in tests now.
I think it could moved to be used fully internally no problem.
