### ISSUE TITLE
Some samples dropped when received in a large clump.

### ISSUE THREAD

**Issue by baffo32** [OpenBCI/OpenBCI_NodeJS#115]
This is resulting in occasional test timeouts, when samples are processed too infrequently to finish in time.

See the extra debugging output at https://travis-ci.org/baffo32/OpenBCI_NodeJS/jobs/171760737#L338 : the system receives many samples (instances of "a0" in the debug bytes), but processes only two of them ("sample 1", "sample 2").

**Comment by aj-ptw** [comment]
This may be the same error as #119

**Comment by baffo32** [comment]
After reviewing the Daisy behavior as determined by the firmware source code I've found that my perceptions here were wrong.  The samples are all processed correctly.  I'm sorry for reporting this as an issue of dropped samples.  It is probably actually an issue of being able to meet the requested samplerate under the extra overhead of the new promise instrumentation.
