### ISSUE TITLE
Bug: droppedPackets on sample 0

### ISSUE THREAD

**Issue by aj-ptw** [OpenBCI/OpenBCI_NodeJS#119]
Keep getting dropped packets on sample 0, thinking this is a bug.

**Comment by aj-ptw** [comment]
I'm not sure I can find the issue here...

**Comment by baffo32** [comment]
We determined this was a feature, not a bug.  When the daisy board is attached, the first sample is corrupt because it is averaged with nothing, so should be dropped.

**Comment by aj-ptw** [comment]
Na I still see it with 8 channel

**Comment by baffo32** [comment]
Oh interesting
