### ISSUE TITLE
CSR dongle installed on Linux, but Node gives error messages

### ISSUE THREAD

**Issue by wjcroft** [OpenBCI/OpenBCI_NodeJS#138]
http://openbci.com/forum/index.php?p=/discussion/963/gui-can-t-find-ganglion-ble-on-linux

Both Node and GUI can't see the CSR dongle.

**Comment by aj-ptw** [comment]
Please open issue on https://github.com/OpenBCI/OpenBCI_NodeJS_Ganglion/issues

**Comment by wjcroft** [comment]
Oops, sorry, will do.
