### ISSUE TITLE
Turn LSL example into a command line executable python script

### ISSUE THREAD

**Issue by teonbrooks** [OpenBCI/OpenBCI_NodeJS#146]
@gabrielibagon wrote a pretty cool [example](https://github.com/OpenBCI/OpenBCI_NodeJS/blob/master/examples/labstreaminglayer/readme.md). we should simplify it to a simple command line executable so we can do something like this:
```
npm start openbci
python openbci_lsl
```
and everything just works

**Comment by teonbrooks** [comment]
cc: @aj-ptw, @rodrigohubner

I can help out on getting the python part set up. just wanted to put it out there. will come back to this issue soon

**Comment by aj-ptw** [comment]
All you need to do is spawn the Python and Node scripts in their own processes, so could be really easy to just have a super script that spawned both children

**Comment by teonbrooks** [comment]
closing because this is no longer a priority. the example above is adequate
