### ISSUE TITLE
impedance testing not operating properly

### ISSUE THREAD

**Issue by aj-ptw** [OpenBCI/OpenBCI_NodeJS#28]
The values that come back from an electrode are too high. There is an issue.

**Comment by pushtheworldllc** [comment]
Well @andrewheusser i wanted to add @teonbrooks here too. I need your help with this! So I have it mainly working, on my dev branch. However all I need to do is taken an FFT at 31.5Hz and use the intensity at that bin as the voltage. I would really love some help with this and this seems right up your guys wheel house. I can teach you how to do the automated testing to get it working and such too!

**Comment by andrewheusser** [comment]
@pushtheworldllc : going in tomorrow?  lets take a look then

**Comment by pushtheworldllc** [comment]
No unfortunately I am heading down to southern jersey for easter weekend but I will be online and can definitely have a google hangout!

**Comment by andrewheusser** [comment]
@pushtheworldllc hey I need a little more context here...where do we want to add an FFT?

**Comment by pushtheworldllc** [comment]
We want to use an FFT to get the amplitude of the channel voltage at 31.5Hz because that’s the frequency of the impedance test signal. Does that make sense?

AJ

**Comment by pushtheworldllc** [comment]
Where we want to add it is in the calculation of impedances!

**Comment by andrewheusser** [comment]
@pushtheworldllc i understand that, can you point me to the point in the code where it should be implemented?

**Comment by pushtheworldllc** [comment]
https://github.com/pushtheworldllc/openbci-js-sdk/blob/dev/openBCISample.js#L215-L237

Please fork my branch if possible! There are a bunch of changes, getting ready for a 0.3

**Comment by andrewheusser** [comment]
ok will do...hmmm, I'm not sure it makes sense to put it here since an FFT requires multiple time points to compute. How will computing an FFT help with the impedance estimates anyway?

**Comment by pushtheworldllc** [comment]
See PR #32 for version 0.3.0 for major changes leading to the resolution of this bug. Need to test.

**Comment by aj-ptw** [comment]
Reopening issue due to #131

**Comment by aj-ptw** [comment]
Final going to close this soon
