### ISSUE TITLE
NTP

### ISSUE THREAD

**Issue by teonbrooks** [OpenBCI/OpenBCI_NodeJS#38]
Let's get this ish settled. Excited about it. Essentially, each data packet will have a time stamp with it. for instance with OpenEXP, when the computer presents, we will have its ntp timestamp for the screen. when we retrieve the data packets, we could modify the packet to have the trigger/tag, then it will be marked in the data. or we can just print a trigger file and do the data correspondence later off-line

**Comment by pushtheworldllc** [comment]
yup yup good thoughts! I'm at OpenBCI three days this week so by Friday should have this firmware ready to be tested!

**Comment by pushtheworldllc** [comment]
just wrapping up automated testing and documentation. this is working though.

**Comment by teonbrooks** [comment]
working?!? :) I am so ready to test this. we will need to have a similar ntp call for openexp, that way, we can write out an presentation event file in NTP time, so it would make it easier for analysis.

**Comment by pushtheworldllc** [comment]
well the module already syncs up with an ntp server and each sample will now have a  time stamp value with it, so you should implement in OpenEXP with a call to `.sntpNow()` when ever you present a stimulus or something i believe

**Comment by pushtheworldllc** [comment]
@teonbrooks I'm really glad you're excited for this new feature! looking forward to getting this merged and being the only SDK that can do time syncing with the openbci :D

**Comment by teonbrooks** [comment]
closing because @andrewjaykeller has added NTP to the module
