### ISSUE TITLE
ADD Ability to output microvolts in samples instead of volts

### ISSUE THREAD

**Issue by aj-ptw** [OpenBCI/OpenBCI_NodeJS#53]
Could add as an option to the constructor

**Comment by pushtheworldllc** [comment]
@teonbrooks thoughts on this feature request?

**Comment by teonbrooks** [comment]
hmm...this flexibility could lead to unintended consequences for packages using the sdk, like visualizations that expect it to be in Volts. would the default be Volt?

**Comment by pushtheworldllc** [comment]
Yeah the default would be volts and I guess somewhere along the way you would specify you want output in uV

**Comment by aj-ptw** [comment]
closing because no interest
