### ISSUE TITLE
ENH: Add Mac/Windows large serialport as option to simulator

### ISSUE THREAD

**Issue by aj-ptw** [OpenBCI/OpenBCI_NodeJS#63]
The Mac and Windows FTDI virtual comm port drivers have big buffers of 4096 which create a fragmented data pulse, there must also be a time component, like every 500 ms it get's cleared, this should be looked into and mimicked in the simulator to provide a better testing environment for graphics developers.

**Comment by baffo32** [comment]
Do you have any more information about how these packets appear?  Do you mean that data is buffered for ~500ms and then drained in one huge go, with many packets in one buffer?

Alternatively, could you throw a `console.log('_processBytes: ' + JSON.stringify('' + data));` into _processBytes and paste some sample output here?

**Comment by aj-ptw** [comment]
It is entirely based on your virtual comm port driver. You have linux, from what i remember so check out your FTDI input buffer size and latency timer. These both work together to determine how often your serial port is dumped.

**Comment by aj-ptw** [comment]
Closed with version `1.4.0`
