### ISSUE TITLE
Don't emit accelerometer array when 0

### ISSUE THREAD

**Issue by aj-ptw** [OpenBCI/OpenBCI_NodeJS#75]
The OpenBCI firmware sends packets at 250Hz, however the accelerometer is only at 25Hz. This leads to accelerometer data only being sent every 10 packets. 

Proposal is to align standard with time synced packets in that an `auxData` `Buffer` 6 bytes long is emitted with every sample and if the data is greater than zero we will omit an `accelData` array with converted and scaled accelerometer values.

**Comment by aj-ptw** [comment]
@haniawni this is a proposal from your request.

**Comment by teonbrooks** [comment]
keeping it periodic will make it a lot easier if you are trying to interpolate this signal to match the sampling rate of the EEG data

**Comment by aj-ptw** [comment]
so you're saying don't change it?

**Comment by teonbrooks** [comment]
I guess I don't understand the problem so clearly. occasionally the data are zeros?

**Comment by aj-ptw** [comment]
yeah at the data rate of 250Hz one would only get valid accel data every 10 samples. So it was confusing for @haniawni as to why some array's had data while others did not.
